eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8080/eureka}
management:
  tracing:
    sampling:
      probability: 1.0
spring:
  jpa:
    hibernate:
      ddl-auto: none #keep this as none, do schema changes using liquibase
      #      this is included to support uppercase values for table names and column names
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    change-log: classpath:db/changelog/postgres/changelog-master.xml
    enabled: true
